// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthwindAPI.Entities {
    
    
    public partial class CustomerDemographicPlural {
        
        [Key()]
        [Display(Name = "Customer type ID")]
        public string CustomerTypeID { get; set; }
        
        [Display(Name = "Customer desc")]
        public string CustomerDesc { get; set; }
        
        /// Child CustomerCustomerDemoes where [CustomerCustomerDemo].[CustomerTypeID] point to this entity (FK_CustomerCustomerDemo)
        public virtual ICollection<CustomerCustomerDemo> CustomerCustomerDemoes { get; set; } = new HashSet<CustomerCustomerDemo>();
    }
}

