// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("CategoryPlural")]
    public class CategoryPluralController : ControllerBase {
        
        private ICategoryPluralBuilder _builder;
        
        public CategoryPluralController(ICategoryPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<CategoryPluralModel>> GetCategoryPlurals() {

            return await _builder.GetCategoryPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(CategoryPluralModel.CategoryID));
            propNames.Add(nameof(CategoryPluralModel.CategoryName));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<CategoryPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetCategoryPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{categoryID}")]
        public async Task<ActionResult> GetCategoryPlural_ByCategoryID(int categoryID) {

             var response = await _builder.GetCategoryPlural_ByCategoryID(categoryID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddCategoryPlural([FromBody]CategoryPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddCategoryPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddCategoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetCategoryPlural_ByCategoryID", new {categoryID = ((CategoryPluralModel)response.Model).CategoryID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateCategoryPlural([FromBody]CategoryPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateCategoryPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateCategoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{categoryID}")]
        public async Task<ActionResult> DeleteCategoryPlural(int categoryID) {

            var response = await _builder.DeleteCategoryPlural(categoryID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteCategoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

