// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("EmployeePlural")]
    public class EmployeePluralController : ControllerBase {
        
        private IEmployeePluralBuilder _builder;
        
        public EmployeePluralController(IEmployeePluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<EmployeePluralModel>> GetEmployeePlurals() {

            return await _builder.GetEmployeePlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(EmployeePluralModel.EmployeeID));
            propNames.Add(nameof(EmployeePluralModel.LastName));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<EmployeePluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetEmployeePlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{employeeID}")]
        public async Task<ActionResult> GetEmployeePlural_ByEmployeeID(int employeeID) {

             var response = await _builder.GetEmployeePlural_ByEmployeeID(employeeID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetEmployeePlural_ByReportsTo/{reportsTo}")]
        public async Task<IList<EmployeePluralModel>> GetEmployeePlural_ByReportsTo(int reportsTo) {

            return await _builder.GetEmployeePlural_ByReportsTo(reportsTo)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddEmployeePlural([FromBody]EmployeePluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddEmployeePlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddEmployeePlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetEmployeePlural_ByEmployeeID", new {employeeID = ((EmployeePluralModel)response.Model).EmployeeID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateEmployeePlural([FromBody]EmployeePluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateEmployeePlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateEmployeePlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{employeeID}")]
        public async Task<ActionResult> DeleteEmployeePlural(int employeeID) {

            var response = await _builder.DeleteEmployeePlural(employeeID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteEmployeePlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

