// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("OrderDetailPlural")]
    public class OrderDetailPluralController : ControllerBase {
        
        private IOrderDetailPluralBuilder _builder;
        
        public OrderDetailPluralController(IOrderDetailPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<OrderDetailPluralModel>> GetOrderDetailPlurals() {

            return await _builder.GetOrderDetailPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(OrderDetailPluralModel.Quantity));
            propNames.Add(nameof(OrderDetailPluralModel.Discount));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<OrderDetailPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetOrderDetailPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{orderID}/{productID}")]
        public async Task<ActionResult> GetOrderDetailPlural_ByOrderIDProductID(int orderID, int productID) {

             var response = await _builder.GetOrderDetailPlural_ByOrderIDProductID(orderID, productID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetOrderDetailPlural_ByOrderID/{orderID}")]
        public async Task<IList<OrderDetailPluralModel>> GetOrderDetailPlural_ByOrderID(int orderID) {

            return await _builder.GetOrderDetailPlural_ByOrderID(orderID)?.ToListAsync();
        }
        
        [HttpGet("GetOrderDetailPlural_ByProductID/{productID}")]
        public async Task<IList<OrderDetailPluralModel>> GetOrderDetailPlural_ByProductID(int productID) {

            return await _builder.GetOrderDetailPlural_ByProductID(productID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddOrderDetailPlural([FromBody]OrderDetailPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddOrderDetailPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddOrderDetailPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetOrderDetailPlural_ByOrderIDProductID", new {orderID = ((OrderDetailPluralModel)response.Model).OrderID, productID = ((OrderDetailPluralModel)response.Model).ProductID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateOrderDetailPlural([FromBody]OrderDetailPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateOrderDetailPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateOrderDetailPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{orderID}/{productID}")]
        public async Task<ActionResult> DeleteOrderDetailPlural(int orderID, int productID) {

            var response = await _builder.DeleteOrderDetailPlural(orderID, productID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteOrderDetailPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

