// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("OrderPlural")]
    public class OrderPluralController : ControllerBase {
        
        private IOrderPluralBuilder _builder;
        
        public OrderPluralController(IOrderPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<OrderPluralModel>> GetOrderPlurals() {

            return await _builder.GetOrderPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(OrderPluralModel.OrderID));
            propNames.Add(nameof(OrderPluralModel.CustomerID));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<OrderPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetOrderPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{orderID}")]
        public async Task<ActionResult> GetOrderPlural_ByOrderID(int orderID) {

             var response = await _builder.GetOrderPlural_ByOrderID(orderID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetOrderPlural_ByCustomerID/{customerID}")]
        public async Task<IList<OrderPluralModel>> GetOrderPlural_ByCustomerID(string customerID) {

            return await _builder.GetOrderPlural_ByCustomerID(customerID)?.ToListAsync();
        }
        
        [HttpGet("GetOrderPlural_ByEmployeeID/{employeeID}")]
        public async Task<IList<OrderPluralModel>> GetOrderPlural_ByEmployeeID(int employeeID) {

            return await _builder.GetOrderPlural_ByEmployeeID(employeeID)?.ToListAsync();
        }
        
        [HttpGet("GetOrderPlural_ByShipVia/{shipVia}")]
        public async Task<IList<OrderPluralModel>> GetOrderPlural_ByShipVia(int shipVia) {

            return await _builder.GetOrderPlural_ByShipVia(shipVia)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddOrderPlural([FromBody]OrderPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddOrderPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddOrderPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetOrderPlural_ByOrderID", new {orderID = ((OrderPluralModel)response.Model).OrderID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateOrderPlural([FromBody]OrderPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateOrderPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateOrderPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{orderID}")]
        public async Task<ActionResult> DeleteOrderPlural(int orderID) {

            var response = await _builder.DeleteOrderPlural(orderID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteOrderPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

