// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("ProductPlural")]
    public class ProductPluralController : ControllerBase {
        
        private IProductPluralBuilder _builder;
        
        public ProductPluralController(IProductPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<ProductPluralModel>> GetProductPlurals() {

            return await _builder.GetProductPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(ProductPluralModel.ProductID));
            propNames.Add(nameof(ProductPluralModel.ProductName));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<ProductPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetProductPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{productID}")]
        public async Task<ActionResult> GetProductPlural_ByProductID(int productID) {

             var response = await _builder.GetProductPlural_ByProductID(productID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetProductPlural_BySupplierID/{supplierID}")]
        public async Task<IList<ProductPluralModel>> GetProductPlural_BySupplierID(int supplierID) {

            return await _builder.GetProductPlural_BySupplierID(supplierID)?.ToListAsync();
        }
        
        [HttpGet("GetProductPlural_ByCategoryID/{categoryID}")]
        public async Task<IList<ProductPluralModel>> GetProductPlural_ByCategoryID(int categoryID) {

            return await _builder.GetProductPlural_ByCategoryID(categoryID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddProductPlural([FromBody]ProductPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddProductPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddProductPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetProductPlural_ByProductID", new {productID = ((ProductPluralModel)response.Model).ProductID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateProductPlural([FromBody]ProductPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateProductPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateProductPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{productID}")]
        public async Task<ActionResult> DeleteProductPlural(int productID) {

            var response = await _builder.DeleteProductPlural(productID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteProductPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

