// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Region")]
    public class RegionController : ControllerBase {
        
        private IRegionBuilder _builder;
        
        public RegionController(IRegionBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<RegionModel>> GetRegions() {

            return await _builder.GetRegions()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(RegionModel.RegionID));
            propNames.Add(nameof(RegionModel.RegionDescription));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<RegionModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetRegions()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{regionID}")]
        public async Task<ActionResult> GetRegion_ByRegionID(int regionID) {

             var response = await _builder.GetRegion_ByRegionID(regionID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddRegion([FromBody]RegionModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddRegion(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetRegion_ByRegionID", new {regionID = ((RegionModel)response.Model).RegionID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateRegion([FromBody]RegionModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateRegion(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{regionID}")]
        public async Task<ActionResult> DeleteRegion(int regionID) {

            var response = await _builder.DeleteRegion(regionID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

