// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("ShipperPlural")]
    public class ShipperPluralController : ControllerBase {
        
        private IShipperPluralBuilder _builder;
        
        public ShipperPluralController(IShipperPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<ShipperPluralModel>> GetShipperPlurals() {

            return await _builder.GetShipperPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(ShipperPluralModel.ShipperID));
            propNames.Add(nameof(ShipperPluralModel.CompanyName));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<ShipperPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetShipperPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{shipperID}")]
        public async Task<ActionResult> GetShipperPlural_ByShipperID(int shipperID) {

             var response = await _builder.GetShipperPlural_ByShipperID(shipperID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddShipperPlural([FromBody]ShipperPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddShipperPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddShipperPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetShipperPlural_ByShipperID", new {shipperID = ((ShipperPluralModel)response.Model).ShipperID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateShipperPlural([FromBody]ShipperPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateShipperPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateShipperPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{shipperID}")]
        public async Task<ActionResult> DeleteShipperPlural(int shipperID) {

            var response = await _builder.DeleteShipperPlural(shipperID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteShipperPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

