// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("SupplierPlural")]
    public class SupplierPluralController : ControllerBase {
        
        private ISupplierPluralBuilder _builder;
        
        public SupplierPluralController(ISupplierPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<SupplierPluralModel>> GetSupplierPlurals() {

            return await _builder.GetSupplierPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(SupplierPluralModel.SupplierID));
            propNames.Add(nameof(SupplierPluralModel.CompanyName));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<SupplierPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetSupplierPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{supplierID}")]
        public async Task<ActionResult> GetSupplierPlural_BySupplierID(int supplierID) {

             var response = await _builder.GetSupplierPlural_BySupplierID(supplierID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddSupplierPlural([FromBody]SupplierPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddSupplierPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddSupplierPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetSupplierPlural_BySupplierID", new {supplierID = ((SupplierPluralModel)response.Model).SupplierID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateSupplierPlural([FromBody]SupplierPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateSupplierPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateSupplierPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{supplierID}")]
        public async Task<ActionResult> DeleteSupplierPlural(int supplierID) {

            var response = await _builder.DeleteSupplierPlural(supplierID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteSupplierPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

