// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace NorthwindAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("TerritoryPlural")]
    public class TerritoryPluralController : ControllerBase {
        
        private ITerritoryPluralBuilder _builder;
        
        public TerritoryPluralController(ITerritoryPluralBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<TerritoryPluralModel>> GetTerritoryPlurals() {

            return await _builder.GetTerritoryPlurals()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(TerritoryPluralModel.TerritoryID));
            propNames.Add(nameof(TerritoryPluralModel.TerritoryDescription));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<TerritoryPluralModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetTerritoryPlurals()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{territoryID}")]
        public async Task<ActionResult> GetTerritoryPlural_ByTerritoryID(string territoryID) {

             var response = await _builder.GetTerritoryPlural_ByTerritoryID(territoryID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetTerritoryPlural_ByRegionID/{regionID}")]
        public async Task<IList<TerritoryPluralModel>> GetTerritoryPlural_ByRegionID(int regionID) {

            return await _builder.GetTerritoryPlural_ByRegionID(regionID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddTerritoryPlural([FromBody]TerritoryPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddTerritoryPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddTerritoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetTerritoryPlural_ByTerritoryID", new {territoryID = ((TerritoryPluralModel)response.Model).TerritoryID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateTerritoryPlural([FromBody]TerritoryPluralModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateTerritoryPlural(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateTerritoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{territoryID}")]
        public async Task<ActionResult> DeleteTerritoryPlural(string territoryID) {

            var response = await _builder.DeleteTerritoryPlural(territoryID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteTerritoryPlural)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

