// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Entities;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public class EmployeePluralBuilder : IEmployeePluralBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public EmployeePluralBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<EmployeePlural, EmployeePluralModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<EmployeePluralModel>(entity);
            }
        }
        
        public IQueryable<EmployeePluralModel> GetEmployeePlurals() {
            return _entities.EmployeePlurals.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.EmployeePlurals.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetEmployeePlural_ByEmployeeID(int employeeID) {
          var query = await Search(_entities.EmployeePlurals, x => x.EmployeeID == employeeID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; EmployeePlural with employeeID = '{employeeID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<EmployeePluralModel> GetEmployeePlural_ByReportsTo(int reportsTo) {

          var query = Search(_entities.EmployeePlurals, x => x.ReportsTo == reportsTo).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddEmployeePlural(EmployeePluralModel model) {
            if (model.ReportsTo != null) {
                var matchReportsTo = _entities.EmployeePlurals.Where(x => x.EmployeeID.Equals(model.ReportsTo));
                if (!matchReportsTo.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.ReportsTo) + " '{model.ReportsTo}' doesn't exist in the system."}; 
                }
            }

           try
           {
                 var entity = _mapper.Map<EmployeePlural>(model);
                _entities.EmployeePlurals.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeePlural added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new EmployeePluralModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateEmployeePlural(EmployeePluralModel model) {

          var query = Search(_entities.EmployeePlurals, x =>  x.EmployeeID == model.EmployeeID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeePlural with _employeeID = '{0}' doesn't exist.",model.EmployeeID)}; 
            }
            if (model.ReportsTo != null) {
                var matchReportsTo = _entities.EmployeePlurals.Where(x => x.EmployeeID.Equals(model.ReportsTo));
                if (!matchReportsTo.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.ReportsTo) + string.Format("EmployeePlural with ReportsTo = '{0}' doesn't exist.", model.ReportsTo)}; 
                }
            }

           try
           {
            EmployeePlural entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeePlural update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteEmployeePlural(int employeeID) {
          var query = Search(_entities.EmployeePlurals, x => x.EmployeeID == employeeID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeePlural with _employeeID = '{0}' doesn't exist.",employeeID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.EmployeePlurals.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("EmployeePlural deleted with values: '{0}'", JsonConvert.SerializeObject(new EmployeePluralModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<EmployeePlural> Search(IQueryable<EmployeePlural> query, Expression<Func<EmployeePlural, bool>> filter) {
            return query.Where(filter);
        }
    }
}

