// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using NorthwindAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public interface ICustomerCustomerDemoBuilder {
        
        IQueryable<CustomerCustomerDemoModel> GetCustomerCustomerDemoes();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetCustomerCustomerDemo_ByCustomerIDCustomerTypeID(string customerID, string customerTypeID);
        
        IQueryable<CustomerCustomerDemoModel> GetCustomerCustomerDemo_ByCustomerID(string customerID);
        
        IQueryable<CustomerCustomerDemoModel> GetCustomerCustomerDemo_ByCustomerTypeID(string customerTypeID);
        
        Task<BuilderResponse> AddCustomerCustomerDemo(CustomerCustomerDemoModel model);
        
        Task<BuilderResponse> UpdateCustomerCustomerDemo(CustomerCustomerDemoModel model);
        
        Task<BuilderResponse> DeleteCustomerCustomerDemo(string customerID, string customerTypeID);
    }
}

