// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using NorthwindAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public interface IEmployeePluralBuilder {
        
        IQueryable<EmployeePluralModel> GetEmployeePlurals();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetEmployeePlural_ByEmployeeID(int employeeID);
        
        IQueryable<EmployeePluralModel> GetEmployeePlural_ByReportsTo(int reportsTo);
        
        Task<BuilderResponse> AddEmployeePlural(EmployeePluralModel model);
        
        Task<BuilderResponse> UpdateEmployeePlural(EmployeePluralModel model);
        
        Task<BuilderResponse> DeleteEmployeePlural(int employeeID);
    }
}

