// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using NorthwindAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public interface IEmployeeTerritoryPluralBuilder {
        
        IQueryable<EmployeeTerritoryPluralModel> GetEmployeeTerritoryPlurals();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetEmployeeTerritoryPlural_ByEmployeeIDTerritoryID(int employeeID, string territoryID);
        
        IQueryable<EmployeeTerritoryPluralModel> GetEmployeeTerritoryPlural_ByEmployeeID(int employeeID);
        
        IQueryable<EmployeeTerritoryPluralModel> GetEmployeeTerritoryPlural_ByTerritoryID(string territoryID);
        
        Task<BuilderResponse> AddEmployeeTerritoryPlural(EmployeeTerritoryPluralModel model);
        
        Task<BuilderResponse> UpdateEmployeeTerritoryPlural(EmployeeTerritoryPluralModel model);
        
        Task<BuilderResponse> DeleteEmployeeTerritoryPlural(int employeeID, string territoryID);
    }
}

