// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using NorthwindAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public interface IOrderPluralBuilder {
        
        IQueryable<OrderPluralModel> GetOrderPlurals();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetOrderPlural_ByOrderID(int orderID);
        
        IQueryable<OrderPluralModel> GetOrderPlural_ByCustomerID(string customerID);
        
        IQueryable<OrderPluralModel> GetOrderPlural_ByEmployeeID(int employeeID);
        
        IQueryable<OrderPluralModel> GetOrderPlural_ByShipVia(int shipVia);
        
        Task<BuilderResponse> AddOrderPlural(OrderPluralModel model);
        
        Task<BuilderResponse> UpdateOrderPlural(OrderPluralModel model);
        
        Task<BuilderResponse> DeleteOrderPlural(int orderID);
    }
}

