// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using NorthwindAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public interface ITerritoryPluralBuilder {
        
        IQueryable<TerritoryPluralModel> GetTerritoryPlurals();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetTerritoryPlural_ByTerritoryID(string territoryID);
        
        IQueryable<TerritoryPluralModel> GetTerritoryPlural_ByRegionID(int regionID);
        
        Task<BuilderResponse> AddTerritoryPlural(TerritoryPluralModel model);
        
        Task<BuilderResponse> UpdateTerritoryPlural(TerritoryPluralModel model);
        
        Task<BuilderResponse> DeleteTerritoryPlural(string territoryID);
    }
}

