// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NorthwindAPI.Entities;
using NorthwindAPI.Models;
using NorthwindAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace NorthwindAPI.Services {
    
    
    public class ProductPluralBuilder : IProductPluralBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public ProductPluralBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<ProductPlural, ProductPluralModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<ProductPluralModel>(entity);
            }
        }
        
        public IQueryable<ProductPluralModel> GetProductPlurals() {
            return _entities.ProductPlurals.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.ProductPlurals.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetProductPlural_ByProductID(int productID) {
          var query = await Search(_entities.ProductPlurals, x => x.ProductID == productID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; ProductPlural with productID = '{productID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<ProductPluralModel> GetProductPlural_BySupplierID(int supplierID) {

          var query = Search(_entities.ProductPlurals, x => x.SupplierID == supplierID).Select(ProjectToModel);

            return query;
        }
        
        public IQueryable<ProductPluralModel> GetProductPlural_ByCategoryID(int categoryID) {

          var query = Search(_entities.ProductPlurals, x => x.CategoryID == categoryID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddProductPlural(ProductPluralModel model) {
            if (model.SupplierID != null) {
                var matchSupplierID = _entities.SupplierPlurals.Where(x => x.SupplierID.Equals(model.SupplierID));
                if (!matchSupplierID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.SupplierID) + " '{model.SupplierID}' doesn't exist in the system."}; 
                }
            }

            if (model.CategoryID != null) {
                var matchCategoryID = _entities.CategoryPlurals.Where(x => x.CategoryID.Equals(model.CategoryID));
                if (!matchCategoryID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.CategoryID) + " '{model.CategoryID}' doesn't exist in the system."}; 
                }
            }

           try
           {
                 var entity = _mapper.Map<ProductPlural>(model);
                _entities.ProductPlurals.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("ProductPlural added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new ProductPluralModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateProductPlural(ProductPluralModel model) {

          var query = Search(_entities.ProductPlurals, x =>  x.ProductID == model.ProductID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("ProductPlural with _productID = '{0}' doesn't exist.",model.ProductID)}; 
            }
            if (model.SupplierID != null) {
                var matchSupplierID = _entities.SupplierPlurals.Where(x => x.SupplierID.Equals(model.SupplierID));
                if (!matchSupplierID.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.SupplierID) + string.Format("ProductPlural with SupplierID = '{0}' doesn't exist.", model.SupplierID)}; 
                }
            }

            if (model.CategoryID != null) {
                var matchCategoryID = _entities.CategoryPlurals.Where(x => x.CategoryID.Equals(model.CategoryID));
                if (!matchCategoryID.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.CategoryID) + string.Format("ProductPlural with CategoryID = '{0}' doesn't exist.", model.CategoryID)}; 
                }
            }

           try
           {
            ProductPlural entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("ProductPlural update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteProductPlural(int productID) {
          var query = Search(_entities.ProductPlurals, x => x.ProductID == productID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("ProductPlural with _productID = '{0}' doesn't exist.",productID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.ProductPlurals.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("ProductPlural deleted with values: '{0}'", JsonConvert.SerializeObject(new ProductPluralModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<ProductPlural> Search(IQueryable<ProductPlural> query, Expression<Func<ProductPlural, bool>> filter) {
            return query.Where(filter);
        }
    }
}

