// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using NorthwindAPI.Entities;

namespace NorthwindAPI.Models {
    
    
    public class AutoMapperProfiles : Profile {
        
        public AutoMapperProfiles() {
            CreateMap<CategoryPlural, CategoryPluralModel>();
            CreateMap<CategoryPluralModel, CategoryPlural>();
            CreateMap<CustomerCustomerDemo, CustomerCustomerDemoModel>();
            CreateMap<CustomerCustomerDemoModel, CustomerCustomerDemo>();
            CreateMap<CustomerDemographicPlural, CustomerDemographicPluralModel>();
            CreateMap<CustomerDemographicPluralModel, CustomerDemographicPlural>();
            CreateMap<CustomerPlural, CustomerPluralModel>();
            CreateMap<CustomerPluralModel, CustomerPlural>();
            CreateMap<EmployeePlural, EmployeePluralModel>();
            CreateMap<EmployeePluralModel, EmployeePlural>();
            CreateMap<EmployeeTerritoryPlural, EmployeeTerritoryPluralModel>();
            CreateMap<EmployeeTerritoryPluralModel, EmployeeTerritoryPlural>();
            CreateMap<OrderDetailPlural, OrderDetailPluralModel>();
            CreateMap<OrderDetailPluralModel, OrderDetailPlural>();
            CreateMap<OrderPlural, OrderPluralModel>();
            CreateMap<OrderPluralModel, OrderPlural>();
            CreateMap<ProductPlural, ProductPluralModel>();
            CreateMap<ProductPluralModel, ProductPlural>();
            CreateMap<Region, RegionModel>();
            CreateMap<RegionModel, Region>();
            CreateMap<ShipperPlural, ShipperPluralModel>();
            CreateMap<ShipperPluralModel, ShipperPlural>();
            CreateMap<SupplierPlural, SupplierPluralModel>();
            CreateMap<SupplierPluralModel, SupplierPlural>();
            CreateMap<TerritoryPlural, TerritoryPluralModel>();
            CreateMap<TerritoryPluralModel, TerritoryPlural>();
        }
    }
}

